#!/bin/bash
set -euo pipefail

# --- Configuration ---
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
PROJECT_ROOT=$(realpath "$SCRIPT_DIR/../../")
TEST_DIR=$(mktemp -d -t binarycoverage_e2e_XXXXXX)
BIN_NAME="calc"
SRC_FILE="$TEST_DIR/$BIN_NAME.c"
BIN_PATH="$TEST_DIR/$BIN_NAME"
LOG_DIR="$TEST_DIR/logs"
SAFE_BIN_DIR="$TEST_DIR/safe_bin"
REPORT_DIR="$TEST_DIR/report"
REPORT_FILE="$REPORT_DIR/report.txt"

# Ensure cleanup
trap "rm -rf '$TEST_DIR'" EXIT

# Load environment (PIN_ROOT)
if [ -f "$PROJECT_ROOT/env" ]; then
    source "$PROJECT_ROOT/env"
fi

# Locate funkoverage tool
FUNKOVERAGE="$PROJECT_ROOT/funkoverage"
if [ ! -f "$FUNKOVERAGE" ]; then
    echo "Error: funkoverage tool not found at $FUNKOVERAGE. Run build.sh first."
    exit 1
fi

# Locate FuncTracer.so
FUNC_TRACER="$PROJECT_ROOT/obj-intel64/FuncTracer.so"
if [ ! -f "$FUNC_TRACER" ]; then
    echo "Error: FuncTracer.so not found at $FUNC_TRACER. Run build.sh first."
    exit 1
fi

export PIN_TOOL_SEARCH_DIR=$(dirname "$FUNC_TRACER")
export LOG_DIR
export SAFE_BIN_DIR

# --- 1. Create Simple Program ---
cat > "$SRC_FILE" <<EOF
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int sum(int a, int b) { return a + b; }
int sub(int a, int b) { return a - b; }
int mult(int a, int b) { return a * b; }
int div_op(int a, int b) { return a / b; }

int main(int argc, char *argv[]) {
    if (argc < 4) {
        printf("Usage: %s <num1> <num2> <op>\n", argv[0]);
        return 1;
    }
    int a = atoi(argv[1]);
    int b = atoi(argv[2]);
    char *op = argv[3];

    if (strcmp(op, "+") == 0) printf("%d\n", sum(a, b));
    else if (strcmp(op, "-") == 0) printf("%d\n", sub(a, b));
    else if (strcmp(op, "*") == 0) printf("%d\n", mult(a, b));
    else if (strcmp(op, "/") == 0) printf("%d\n", div_op(a, b));
    else printf("Unknown op\n");
    return 0;
}
EOF

# --- 2. Compile ---
echo "Compiling $SRC_FILE..."
gcc -g -gdwarf-4 "$SRC_FILE" -o "$BIN_PATH"

# --- 3. Wrap ---
echo "Wrapping binary..."
"$FUNKOVERAGE" wrap "$BIN_PATH"

# Verify wrapper
if ! grep -q "Pin Wrapper generated by Go tool funkoverage" "$BIN_PATH"; then
    echo "Error: Binary not wrapped correctly."
    exit 1
fi
echo "Binary wrapped successfully."

# --- 4. Run (Test Case 1: Sum) ---
echo "Running test case 1 (Sum)..."
"$BIN_PATH" 10 20 +

# --- 5. Verify Invariants (Coverage) ---
echo "Generating report..."
mkdir -p "$REPORT_DIR"
"$FUNKOVERAGE" report "$LOG_DIR" "$REPORT_DIR" --formats txt,xml > "$REPORT_FILE"

# Check if report exists
if [ ! -f "$REPORT_FILE" ]; then
    echo "Error: Report file not found at $REPORT_FILE"
    exit 1
fi

XML_REPORT="$REPORT_DIR/coverage_calc.xml"
if [ ! -f "$XML_REPORT" ]; then
    echo "Error: XML Report for calc not found at $XML_REPORT"
    ls -l "$REPORT_DIR"
    exit 1
fi

echo "Checking coverage invariants in $XML_REPORT..."

# "sum" should be called (marked with ✓)
if ! grep -q "✓ sum" "$XML_REPORT"; then
    echo "Error: Function 'sum' should be called (✓ sum), but was not found."
    exit 1
fi

# "sub" should be uncalled (marked with ✗)
if ! grep -q "✗ sub" "$XML_REPORT"; then
     echo "Error: Function 'sub' should be uncalled (✗ sub), but was not found."
     # Debug: show file content
     cat "$XML_REPORT"
     exit 1
fi

# --- 6. Add Test Case (Sub) ---
echo "Running test case 2 (Sub)..."
"$BIN_PATH" 10 20 -

echo "Regenerating report..."
"$FUNKOVERAGE" report "$LOG_DIR" "$REPORT_DIR" --formats txt,xml > "$REPORT_FILE"

echo "Checking updated coverage..."
# Now "sub" should be called (marked with ✓)
if ! grep -q "✓ sub" "$XML_REPORT"; then
    echo "Error: Function 'sub' should be called now, but it is not."
    cat "$XML_REPORT"
    exit 1
fi

# --- 7. Unwrap ---
echo "Unwrapping binary..."
"$FUNKOVERAGE" unwrap "$BIN_PATH"

# Verify unwrap
if grep -q "Pin Wrapper generated by Go tool funkoverage" "$BIN_PATH"; then
    echo "Error: Binary not unwrapped."
    exit 1
fi

# Check if it's an ELF
if ! file "$BIN_PATH" | grep -q "ELF"; then
     echo "Error: Restored file is not an ELF binary."
     exit 1
fi

echo "E2E Test Passed!"
