name: Build check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install required tools
        run: sudo apt update && sudo apt install -y g++ curl

      - name: Make build.sh executable
        run: chmod +x ./build.sh

      - name: Run build script
        run: ./build.sh
